# Generated by Django 6.0.6 on 2026-09-24 21:45

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('percent_off', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('scope', models.CharField(choices=[('ORDER', 'Whole order'), ('PRODUCTS', 'Specific products')], default='ORDER', max_length=8)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('products', models.ManyToManyField(blank=True, related_name='coupons', to='products.product')),
            ],
            options={
                'ordering': ['-starts_at', 'code'],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('starts_at'))), name='coupon_expires_after_it_starts', violation_error_message='The end must come after the start.')],
            },
        ),
    ]
